import React from "react";
import Head from "next/head";
import Navbar from "../../../components/navbar";
import Hero from "../../../components/hero";
import { client, urlFor } from "../../../client";

export default function Projects({ casestudies }) {
  console.log(`casestudies`, casestudies);

  return (
    <div>
      <Head>
        <title>Freemodel</title>
        {/* <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/ENicon.svg" /> */}
      </Head>

      <Navbar />
      <main>
        <Hero hero={{ title: "Check our work." }} />
      </main>
    </div>
  );
}

export const getStaticProps = async () => {
  const query = ` *[_type == "caseStudy"] {
      _id,
      title,
      mainImage,
      slug {
        current
      }
      }`;

  const casestudies = await client.fetch(query);

  return {
    props: {
      casestudies,
    },

    revalidate: 10,
  };
};
