import React from "react";
import { useRouter } from "next/router";
import { client, urlFor } from "../../../../client";
import Head from "next/head";
import Navbar from "../../../../components/navbar";

import Footer from "../../../../components/footer";

const ProjectSlug = ({ item }) => {
  console.log(`item`, item);
  return (
    <div>
      <Head>
        <title>Freemodel</title>
        {/* <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/ENicon.svg" /> */}
      </Head>

      <Navbar />

      <main>{item.statename}</main>
      <Footer />
    </div>
  );
};

export default ProjectSlug;

export const getServerSideProps = async ({ params }) => {
  const { slug = "" } = params;

  const query = `*[_type == "states" && slug.current == $slug][0] {
    _id,
    statename,
    "cities": *[_type == "cities" && references(^._id)]{
        _id,
        name,
        "projects": *[_type == "projects" && references(^._id)]{
            _id,
            title,
            slug,
            mainImage,
            dollarprofit,
            percentreturn,
            soldfor,
        }
    }
    }`;

  const states = await client.fetch(query, { slug: slug });

  return {
    props: {
      item: states,
    },
  };
};
