import React from "react";
import Head from "next/head";
import Navbar from "../../components/navbar";
import Hero from "../../components/hero";
import Bluebar from "../../components/bluebar";
import Footer from "../../components/footer";
import LearnSection from "../../components/about-us/learnsection";
import Carousel from "../../components/caroucel";

export default function AboutUs() {
  const faqsList = [
    {
      q: "What are some random questions to ask?",
      a: "That's exactly the reason we created this random question generator. There are hundreds of random questions to choose from so you're able to find the perfect random question.",
    },
    {
      q: "Do you include common questions?",
      a: "This generator doesn't include most common questions. The thought is that you can come up with common questions on your own so most of the questions in this generator.",
    },
    {
      q: "Can I use this for 21 questions?",
      a: "Yes! there are two ways that you can use this question generator depending on what you're after. You can indicate that you want 21 questions generated.",
    },
  ];

  const projects = [
    {
      title: "Lake Top Majesty",
      image: "/testhouse.jpg",
      beds: "2",
      baths: "1",
      duration: "4 months",
    },
    {
      title: "Mountain Top Majesty",
      image: "/testhouse.jpg",
      beds: "2",
      baths: "1",
      duration: "4 months",
    },
    {
      title: "Tree Top Majesty",
      image: "/testhouse.jpg",
      beds: "2",
      baths: "1",
      duration: "4 months",
    },
    {
      title: "Dessert Top Majesty",
      image: "/testhouse.jpg",
      beds: "2",
      baths: "1",
      duration: "4 months",
    },
    {
      title: "Beach Top Majesty",
      image: "/testhouse.jpg",
      beds: "2",
      baths: "1",
      duration: "4 months",
    },
    {
      title: "City Top Majesty",
      image: "/testhouse.jpg",
      beds: "2",
      baths: "1",
      duration: "4 months",
    },
  ];

  return (
    <div>
      <Head>
        <title>Freemodel</title>
        {/* <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/ENicon.svg" /> */}
      </Head>

      <Navbar />

      <main>
        <Hero hero={{ title: "A little about us." }} buttontext="Let's Talk" />

        <Bluebar body="Our founding team has deep experience in both the residential real estate and software industries." />

        <LearnSection faqsList={faqsList} />

        <div className="text-center py-32 bg-FM-blue">
          <Carousel projects={projects} />
        </div>
      </main>

      <Footer />
    </div>
  );
}
