import React from "react";
import Head from "next/head";
import Navbar from "../../components/navbar";
import Hero from "../../components/hero";
import Footer from "../../components/footer";
import ThreeSection from "../../components/careers/threesection";

export default function Career() {
  return (
    <div>
      <Head>
        <title>Freemodel</title>
        {/* <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/ENicon.svg" /> */}
      </Head>

      <Navbar />

      <main>
        <Hero hero={{ title: "A little about us." }} buttontext="Let's Talk" />

        <ThreeSection />

        <h1 className="text-4xl text-center font-bold my-20">We're Hiring!</h1>
        <div className="bg-stone-500 h-96 flex items-center justify-center">
          add jobs here
        </div>
      </main>

      <Footer />
    </div>
  );
}
