import React from "react";
import Head from "next/head";
import Navbar from "../../components/navbar";
import Hero from "../../components/hero";
import Bluebar from "../../components/bluebar";
import Steps from "../../components/steps";
import Footer from "../../components/footer";
import { client } from "../../client";

export default function HowItWorks({ footer}) {
  let data = {
    title: "Let us take care of everything.",
    mainImage: {
      asset: {
        url: "/images/hero.jpg",
      },
    },
  };


  return (
    <div>
      <Head>
        <title>Freemodel</title>
        {/* <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/ENicon.svg" /> */}
      </Head>

      <Navbar />

      <main>
        <Hero hero={data} buttontext={"Let's Talk"} />
        <Bluebar theme={"titletext"} />
        <Steps />
      </main>

      <Footer data={footer} />
    </div>
  );
}

 export const getStaticProps = async () => {
  const footer = await client.fetch(`*[_type == "footersettings"][0]{
    footerimage {
      hotspot,
      crop,
      asset->{
        _id,
        url
      }
    },
    leftItems,
    rightItems,
  }`);

  return {
    props: {
      footer,
    },

    revalidate: 10,
  };
};