import React from "react";
import Head from "next/head";
import Image from "next/image";
import { client, urlFor } from "../../client";
import Navbar from "../../components/navbar";
import Hero from "../../components/hero";
import Sixgrid from "../../components/sixgrid";
import Rightleftright from "../../components/rightleftright";
import Carousel from "../../components/caroucel";
import Quoteslider from "../../components/quoteslider/quoteslider";
import Homelocation from "../../components/homelocation";
import Footer from "../../components/footer";
import "keen-slider/keen-slider.min.css";

export default function Home({ data }) {
  const projects = [
    {
      title: "Lake Top Majesty",
      image: "/testhouse.jpg",
      beds: "2",
      baths: "1",
      duration: "4 months",
    },
    {
      title: "Mountain Top Majesty",
      image: "/testhouse.jpg",
      beds: "2",
      baths: "1",
      duration: "4 months",
    },
    {
      title: "Tree Top Majesty",
      image: "/testhouse.jpg",
      beds: "2",
      baths: "1",
      duration: "4 months",
    },
    {
      title: "Dessert Top Majesty",
      image: "/testhouse.jpg",
      beds: "2",
      baths: "1",
      duration: "4 months",
    },
    {
      title: "Beach Top Majesty",
      image: "/testhouse.jpg",
      beds: "2",
      baths: "1",
      duration: "4 months",
    },
    {
      title: "City Top Majesty",
      image: "/testhouse.jpg",
      beds: "2",
      baths: "1",
      duration: "4 months",
    },
  ];

  return (
    <div>
      <Head>
        <title>Freemodel</title>
        {/* <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/ENicon.svg" /> */}
      </Head>

      <Navbar />

      <main>
        <Hero hero={data} buttontext={"Let's Talk"} />
        <Sixgrid />
        <Rightleftright />

        <div className="text-center my-40">
          <h1 className="text-5xl text-center text-black font-bold mb-20">
            Why Agents Love Us
          </h1>
          <Carousel projects={projects} />
        </div>
        <Quoteslider />
        <Homelocation />

        <div className="px-4 py-16 bg-FM-blue md:px-24 lg:px-8 lg:py-20">
          <div className="grid gap-10 mx-auto sm:max-w-xl md:max-w-full lg:max-w-screen-xl lg:grid-cols-2">
            <div className="lg:pr-10 md: my-auto">
              <h5 className="mb-4 text-4xl text-white font-extrabold leading-none">
                Not in your City?
              </h5>
              <p className="mb-6 text-white">
                We will let you know when we are!
              </p>
            </div>
            <div></div>
          </div>
        </div>
      </main>
      <Footer />
    </div>
  );
}

export const getStaticProps = async () => {
  const mainquery = `*[_type == "home"][0] {
    _id,
    title,
    mainImage,
    overview,
}`;

  const data = await client.fetch(mainquery);

  return {
    props: {
      data,
    },

    revalidate: 10,
  };
};
