import React from "react";
import Head from "next/head";
import Image from "next/image";
import { client, urlFor } from "../../client";
import Navbar from "../../components/navbar";
import Hero from "../../components/hero";
import Sixgrid from "../../components/sixgrid";
import Rightleftright from "../../components/rightleftright";
import Carousel from "../../components/caroucel";
import Quoteslider from "../../components/quoteslider";
import Homelocation from "../../components/homelocation";
import Footer from "../../components/footer";

export default function Home({ data }) {
  console.log(`data`, data);

  return (
    <div>
      <Head>
        <title>Freemodel</title>
        {/* <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/ENicon.svg" /> */}
      </Head>

      <Navbar />

      <main
      //className={`flex min-h-screen flex-col items-center justify-between p-24`}
      >
        <Hero hero={data} />
        <Sixgrid />
        <Rightleftright />
        <Carousel />
        <Quoteslider />
        <Homelocation />
      </main>
      <Footer />
    </div>
  );
}

export const getStaticProps = async () => {
  const mainquery = `*[_type == "home"][0] {
    _id,
    title,
    mainImage,
    overview,
}`;

  const data = await client.fetch(mainquery);

  return {
    props: {
      data,
    },

    revalidate: 10,
  };
};
