import React from "react";
import Head from "next/head";
import Image from "next/image";
import { client, urlFor } from "../../client";
import Navbar from "../../components/navbar";
import Hero from "../../components/hero";
import Sixgrid from "../../components/index/sixgrid";
import Rightleftright from "../../components/index/rightleftright";
import Carousel from "../../components/caroucel";
import Quoteslider from "../../components/quoteslider";
import Homelocation from "../../components/index/homelocation";
import Footer from "../../components/footer";
import "keen-slider/keen-slider.min.css";

export default function Home({ data, states }) {
  console.log("states", states);

  return (
    <div>
      <Head>
        <title>Freemodel</title>
        {/* <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/ENicon.svg" /> */}
      </Head>

      <Navbar />

      <main>
        <Hero hero={data} buttontext={"Let's Talk"} />
        <Sixgrid
          title={data.sec1title}
          imageArray={data.imageArray}
          buttontext={data.sec1button}
        />
        <Rightleftright
          title={data.sec2title}
          imageArray={data.sec2imageArray}
        />

        <div className="text-center my-40">
          <h1 className="text-5xl text-center text-black font-bold mb-20">
            {data.sec3title}
          </h1>
          <Carousel projects={data.projects} />
        </div>

        <Quoteslider
          title="Why Agents Love Us"
          testimonials={data.testimonials}
        />

        <Homelocation states={states} buttontext={data.statesbutton} />

        <div className="px-4 py-16 bg-FM-blue md:px-24 lg:px-8 lg:py-20">
          <div className="grid gap-10 mx-auto sm:max-w-xl md:max-w-full lg:max-w-screen-xl lg:grid-cols-2">
            <div className="lg:pr-10 md: my-auto">
              <h5 className="mb-4 text-4xl text-white font-extrabold leading-none">
                {data.htmltitle}
              </h5>
              <p className="mb-6 text-white">{data.htmlbody}</p>
            </div>
            <div>
              {/* html form */}
              <div
                dangerouslySetInnerHTML={{
                  __html: data.htmlform,
                }}
              />
            </div>
          </div>
        </div>
      </main>
      <Footer />
    </div>
  );
}

export const getStaticProps = async () => {
  const mainquery = `*[_type == "home"][0] {
    _id,
    title,
    mainImage,
    sec1title,
    imageArray,
    sec1button,
    sec2title,
    sec2imageArray,
    sec2button,
    sec3title,
    projects []-> {
      _id,
      title,
      mainImage,
      beds,
      baths,
      duration,
      slug,
      bool
    },
    testimonials[]->{
      _id,
      testimonialperson,
      testimonialquote,
      testimonialimage,
      testimonialposition,
      brokerage,
    },
    statesbutton,
    htmltitle,
    htmlbody,
    htmlform, 
}`;

  const states = await client.fetch(`*[_type == "states"]{
  _id,
  statename,
  stateabbr,
  hero,
  slug,
  image
  
}`);

  const data = await client.fetch(mainquery);

  return {
    props: {
      data,
      states,
    },

    revalidate: 10,
  };
};
