import React from "react";
import Head from "next/head";
import Navbar from "../../components/navbar";
import Hero from "../../components/hero";
import Footer from "../../components/footer";

export default function LetsTalk() {
  return (
    <div>
      <Head>
        <title>Freemodel</title>
        {/* <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/ENicon.svg" /> */}
      </Head>

      <Navbar />

      <main>
        <Hero hero={{ title: "Let's Talk" }} />

        <div className="bg-stone-500 h-96 flex items-center justify-center">
          add form here
        </div>
      </main>

      <Footer />
    </div>
  );
}
