import React from "react";
import Head from "next/head";
import Navbar from "../../components/navbar";
import Hero from "../../components/hero";
import Bluebar from "../../components/bluebar";
import Footer from "../../components/footer";
import MediaList from "../../components/media/medialist";
import { client, urlFor } from "../../client";

export default function Media({ data, mediadata }) {
  return (
    <div>
      <Head>
        <title>Freemodel</title>
        {/* <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/ENicon.svg" /> */}
      </Head>

      <Navbar />

      <main>
        <Hero
          hero={{ title: mediadata.title }}
          buttontext={mediadata.titlebutton}
          image={urlFor(mediadata.mainImage).url()}
        />

        <Bluebar
          body={
            "For any press inquiries please contact marketing@freemodel.com."
          }
        />

        <MediaList media={data} />
      </main>

      <Footer />
    </div>
  );
}

export const getStaticProps = async () => {
  const mainquery = `*[_type == "media"]{
    name,
    url,
    image {
      hotspot,
      crop,
      asset->{
        _id,
        url
      }
    }
  }`;

  const mediapage = `*[_type == "mediapage"][0]{
    title,
    mainImage {
      crop {
        _type,
        top,
        bottom,
        left,
        right
      },
      hotspot {
        _type,
        x,
        y,
        height,
        width
      },
      asset-> {
        _id,
        url
      }
    },
    titlebutton,
    bluetitle,
  }
  `;

  const data = await client.fetch(mainquery);
  const mediadata = await client.fetch(mediapage);

  return {
    props: {
      data: data,
      mediadata: mediadata,
    },

    revalidate: 10,
  };
};
