import Head from "next/head";
import Navbar from "../../components/navbar";
import Footer from "../../components/footer";
import { client, urlFor } from "../../client";
import Hero from "../../components/hero";
import Paragraph from "../../components/paragraph";

export default function ThankYouAgent({ data, footer }) {
  return (
    <div>
      <Head>
        <title>Freemodel</title>
        {/* <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/ENicon.svg" /> */}
      </Head>

      <Navbar data={footer.navbar} />

      <main>
        <Hero
          hero={{ title: data.title }}
          buttontext={data.titlebutton}
          image={urlFor(data.mainImage).url()}
        />

        <div className="text-center !text-2xl">
          <Paragraph text={data.body} />
        </div>
      </main>

      <Footer data={footer} />
    </div>
  );
}

export const getStaticProps = async () => {
  const data = await client.fetch(`*[_type == "supportpage"][0]{
            title,
            mainImage{
                hotspot,
                crop,
                asset->{
                    _id,
                    url
                }
            },
            titlebutton,
            body
        }`);

  const footer = await client.fetch(`*[_type == "footersettings"][0]{
        footerimage {
          hotspot,
          crop,
          asset->{
            _id,
            url
          }
        },
        linkedin,
        instagram,
        facebook,
        pinterest,
        leftItems,
        rightItems,
        navbar
      }`);

  return {
    props: {
      footer,
      data,
    },

    revalidate: 10,
  };
};
