import React from "react";
import Head from "next/head";
import Navbar from "../../../components/navbar";
import Footer from "../../../components/footer";
import { client } from "../../../client";

export default function Blog({ data, footer }) {
  console.log("data", data);
  return (
    <div>
      <Head>
        <title>Freemodel</title>
        {/* <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/ENicon.svg" /> */}
      </Head>

      <Navbar />
      <main>
        <h1 className="text-4xl text-center font-bold my-20">Blog</h1>
      </main>

      <Footer data={footer} />
    </div>
  );
}

export const getStaticProps = async () => {
  const mainquery = await client.fetch(`*[_type == "post"]{
    title,
    slug,
    publishedAt,
    projectdirector->{
      name,
      slug
    },
    mainImage {
      hotspot,
      crop,
      asset->{
        _id,
        url
      }
    },
    body,
    excerpt,
  }`);

  const footer = await client.fetch(`*[_type == "footersettings"][0]{
    footerimage {
      hotspot,
      crop,
      asset->{
        _id,
        url
      }
    },
    linkedin,
      instagram,
      facebook,
      pinterest,
    leftItems,
    rightItems,
  }`);

  return {
    props: {
      data: mainquery,
      footer,
    },

    revalidate: 10,
  };
};
